### ISSUE TITLE
Consider compiling from SVN

### ISSUE THREAD

**Issue by RX4NT9UP** [flathub/com.dosbox.DOSBox#1]
How about using a newer version for the flatpak? DOSBOX .74 is 8 years old and there's no indication there will be another release anytime soon, if ever. I can't comment as to why this is, but in the intervening years there's been a lot of updates and fixes. It would be very useful to have an easy way to access those.

Something similar to this:
https://aur.archlinux.org/packages/dosbox-svn/

Thanks

**Comment by AsciiWolf** [comment]
I am not sure if Flathub is ok with devel versions of applications. Maybe @TingPing will know more about this?

Anyway, thanks for the AUR package link, I will look at it. I would also love to have the unofficial [Glide](http://www.si-gamer.net/gulikoza/glide.html) patch enabled if possible.

**Comment by barthalion** [comment]
It isn't ok, but I think we should have some exceptions. Dolphin is another instance of application that could benefit from using git snapshots.

**Comment by TingPing** [comment]
What is it with emulators being scared of releasing versions... At 8 years since a release yea it probably makes sense to add an exception. It does become completely arbitrary when you feel like updating though.

**Comment by Pixelnarium** [comment]
If tracking svn HEAD is not a good option there is a [0.74_2 branch](https://sourceforge.net/p/dosbox/code-0/4136/tree/dosbox/branches/0_74_2/) that [fixes some issues](https://sourceforge.net/p/dosbox/code-0/4123/) with 0.74.

Otherwise I copied this project here to test a [DOSBoxSVN](https://github.com/Pixelnarium/flatpak/tree/master/com.dosbox.DOSBoxSVN). Seems to work just fine.

**Comment by AsciiWolf** [comment]
@Pixelnarium Cool, I didn't know about this branch. Thanks for the info!

**Comment by bam80** [comment]
https://github.com/Pixelnarium/flatpak/tree/master/com.dosbox.DOSBox

**Comment by bam80** [comment]
> I would also love to have the unofficial Glide patch enabled if possible.

What about having patches here? The drawback would be it seems does not supported in the official forum: https://www.vogons.org/viewtopic.php?f=41&t=62203&p=725128&sid=a6a14364f923dac8b5b96e859c2156c9#p725128

**Comment by AsciiWolf** [comment]
What license is the Glide patch and could it be used with the non-svn version of DOSBox?

**Comment by bam80** [comment]
Personally I don't need Glide, but seems people have demand: https://github.com/Pixelnarium/flatpak/issues/1#issuecomment-452231155

**Comment by AsciiWolf** [comment]
I was thinking about including the Glide patch as well (I really like the idea of running older Windows games in DOSBox), but as I said, I don't know what the license of the patch is and I am also not sure if I can apply the patch on the actual stable DOSBox code. I probably won't be switching to the SVN version for this Flatpak because the DOSBox development seems to be alive again and new stable release is planned.

**Comment by Pixelnarium** [comment]
Yeah DOSBOX 0.75 is coming and nobody knows if [those patches I used](https://github.com/voyageur/openglide/tree/master/platform/dosbox) are going to be updated if they break. Also the Glide patches are not without problems.

Another thing is that I think that flathub should not arbitrarily patch features into upstream programs without changing the name.

**Comment by Pixelnarium** [comment]
DOSBOX 0.74-3 is out. It has some security fixes: https://www.dosbox.com/

0.75 is also mentioned as a little delayed.

**Comment by AsciiWolf** [comment]
DOSBox development is no longer dead so there's no reason to use SVN build. Closing this issue.
